# -*- coding: utf-8 -*-
"""Semana02-03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A0zjWvrIpcSoMlXxlZa0wymXhGhw18Nm

#SEMANA 02

Danahe Arleni Gutierrez Gutierrez

Temas:
  1. Números
  2. Variables
  3. Manejo de cadenas
  4. Ingreso por el teclado
  5. Operadores

3. Manejo de cadenas
"""

cadena="UNTELS"

cadena

cadena[1]

cadena[-1]

len(cadena)

#desde hata 1 ante
cadena[1:4]

#para mostrar una cadena en mayuscula utilizamos upper()
cadena.upper()

#para mostrar una cadena en minuscula utilizamos lower()
cadena.lower()

# Generar una lista a partir de una cadena. split()
cadena.split()

# Generar lista utilizando un criterio de separacion
cadena.split("U")

# forma clasica, concatenar con +
nombre = "Danahe Gutierrez"
print("Buenas tardes" + nombre)

#utilizando el . formant()
nombre = "Danahe Gutierrez"
edad= 20
print("hola {} ya se que tienes {} años". format(nombre, edad))

# dar formaato a numeros con muchos decimaales
resultado = 10/3
print(f"10/3 es = {resultado}")
print(f"10/3 es = {resultado:1.3f}")

#dar formato con f
#la funcion f, esta disponible desde la version 3.6
nombre = "Daneli Levaano"
edad = 8
print(f"buenos dias {nombre}, ya se que tienes {edad} años")