# -*- coding: utf-8 -*-
"""Semana02-04.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y97nPog1wYwIM-oxjIvTekFnI5zjoobI

#SEMANA 02

Danahe Arleni Gutierrez Gutierrez

Temas:
  1. Números
  2. Variables
  3. Manejo de cadenas
  4. Ingreso por el teclado
  5. Operadores

4. Ingreso por el teclado
"""

#funcion input()
print("¿cual es tu nombre?")
nombre = input()
print("hola "+ nombre)

#cuando ingrese un valor por teclado lo hace como cadena
print("numero 1: ")
numero1 = input()
print("numero 2: ")
numero2 = input()
numero3 = int(numero1) + int(numero2)
print(f"El resultado es {numero3}")