# -*- coding: utf-8 -*-
"""Semana02-02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15vCxeFNOOKVwGkX7Y0Z0EBCEIaTZaYEJ

#SEMANA 02

Danahe Arleni Gutierrez Gutierrez

Temas:
  1. Números
  2. Variables
  3. Manejo de cadenas
  4. Ingreso por el teclado
  5. Operadores

2. Variables

Siempre deben iniciar con una letra o un guion abajo
"""

edad=41

edad

nombre = "Danahe"

nombre

apellido = "Gutierrez Gutierrez"

apellido

nombrecompleto = nombre + apellido

nombrecompleto

nombrecompleto = " "